services:
  frontend:
    build: ./frontend
    ports:
      - 4000:4000
    networks:
      - network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  network:
