services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - network

  backend:
    build: ./backend
    ports:
      - 4000:4000
    networks:
      - network

networks:
  network:
